version: 2
jobs:
  build:
    docker:

      - image: circleci/node:8
        environment:
          NODE_ENV: production

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - dependencies-{{ checksum "package.json" }}

      - run:
          name: Install dependencies
          command: |
            npm install
            npm install --only=dev

      - save_cache:
          paths:
            - ./node_modules
          key: dependencies-{{ checksum "package.json" }}

      - run:
          name: Build assets
          command: |
            npm run build
            cp -R ./public/* ./dist

      - store_artifacts:
          path: test-reports
          destination: test-reports

      - persist_to_workspace:
          root: dist
          paths: .

  deploy-staging:
    machine:
        enabled: true
    working_directory: ~/repo
    environment:
      DOKKU_REMOTE: "$DOKKU_REMOTE_STAGING"
    steps:
      - checkout
      - attach_workspace:
          at: dist

      - run:
          name: Commit assets
          command: |
            git add dist
            git commit -m "Add assets"

      - run:
          name: Deploy to Dokku
          command: |
            git remote add dokku $DOKKU_REMOTE
            echo Pushing to Dokku...
            git push dokku develop:master &>/dev/null

  deploy-production:
    machine:
        enabled: true
    working_directory: ~/repo
    environment:
      DOKKU_REMOTE: "$DOKKU_REMOTE_PRODUCTION"
    steps:
      - checkout
      - attach_workspace:
          at: dist

      - run:
          name: Commit assets
          command: |
            git add dist
            git commit -m "Add assets"

      - run:
          name: Deploy to Dokku
          command: |
            git remote add dokku $DOKKU_REMOTE
            echo Pushing to Dokku...
            git push dokku master:master &>/dev/null

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy-staging:
          filters:
            branches:
              only: develop
          requires:
            - build
      - deploy-production:
          filters:
            branches:
              only: master
          requires:
            - build
